### ISSUE TITLE
Incorrect simulation results with h1.urdf from the newton-assets repo

### ISSUE THREAD

**Issue by Kenny-Vilella** [newton-physics/newton#911]
When simulating either `h1.urdf` or `h1_with_hand.urdf` from the newton-assets repository, I obtained weird simulation results even when disabling contact.
The same files are simulating fine when using directly mujoco C, which indicate an issue in Newton.

When enabling the mujoco viewer along with the Newton viewer, I can see very different visual results.
The results from the mujoco viewer show a distorted body that explain well the results shown in the Newton solver.

All this points to an issue in the Newton model builder.

Picture below for reference:

<img width="2426" height="1032" alt="Image" src="https://github.com/user-attachments/assets/5e23248e-b027-45f7-a14d-f7fefab8c2d6" />

**Comment by Kenny-Vilella** [comment]
A better image showing the collision mesh in both window:

<img width="1622" height="882" alt="Image" src="https://github.com/user-attachments/assets/cddbb8ee-be12-4068-be4f-c82c78a499c4" />

**Comment by eric-heiden** [comment]
@Kenny-Vilella/@jvonmuralt not sure if this is a joint ordering issue that causes a mismatch in the kinematics, I've fixed that here: https://github.com/newton-physics/newton/pull/889.
Also note that Newton's kinematics function currently assume that parent joints come before child joints (so both DFS and BFS ordering are fine) but this may not be given if a URDF is parsed in its original joint ordering, see https://github.com/newton-physics/newton/issues/910.

**Comment by Kenny-Vilella** [comment]
Yes your PR solves most of the issue !
I can still see some weird inertia, but at least the robot does something that makes sense.

**Comment by jvonmuralt** [comment]
I can confirm wrong masses and inertia when ignore_inertial_definitions is set to True. When False, the parsing seems to be entirely correct

**Comment by jvonmuralt** [comment]
@eric-heiden  whats the idea of ignore_inertial_definitions? If I understood it right, we cannot get the right masses and inertias as it relies on some default density to compute them. I could only think of reading the masses from urdf and scaling based on that inertias, but I am not sure whats the original pupose of this ignore_inertial_definitions flag?

**Comment by eric-heiden** [comment]
@jvonmuralt We added this flag becomes some URDF have wrong inertial definitions in practice so it is better to ignore them. I believe this might be even the default behavior in pybullet, @erwincoumans can confirm.

In any case, the inertia computed from the default density are not scaled correctly, but do the inertia boxes roughly have the correct orientation to what you expect for this model? See the inertia box visualization in ViewerGL.

**Comment by jvonmuralt** [comment]
yes, they do, it is only a scaling problem that I see with h1

**Comment by jvonmuralt** [comment]
@eric-heiden  can we close this bug if thats only scaling?

**Comment by adenzler-nvidia** [comment]
@jvonmuralt ignore_inertial_definitions is gone now, is this still an issue?

**Comment by jvonmuralt** [comment]
@adenzler-nvidia I dont see the flag being gone but I see the default is False. So under default value there is no scaling issue and behavior is correct.
